# docker-compose.yml

services:
  bot:
    build: .
    ports:
      - "8004:8004"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JIRA_BASE_URL=${JIRA_BASE_URL}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL}
      - CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - MAX_SLACK_MSG_LENGTH=${MAX_SLACK_MSG_LENGTH}
      # Make sure to include these environment variables if they are used by your bot
      - RUNWAY_API_KEY=${RUNWAY_API_KEY}
      - RUNWAY_BASE_URL=${RUNWAY_BASE_URL:-https://api.runway.team/v1}
      - RUNWAY_ORG_ID=${RUNWAY_ORG_ID}
      - RUNWAY_APP_ID=${RUNWAY_APP_ID}
    networks: # ADD THIS SECTION TO YOUR BOT SERVICE
      - gidchatbot_default # Connect the bot to the same external network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: "http bot:8004"
    ports:
      - "4040:4040"
    networks:
      - gidchatbot_default # This is already correct in your snippet

networks:
  gidchatbot_default:
    external: true # This is correct for an existing network