# docker-compose.yml

services:
  bot:
    build: .
    ports:
      - "8004:8004"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JIRA_BASE_URL=${JIRA_BASE_URL}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL}
      - CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CONFLUENCE_SPACE_KEY=${CONFLUENCE_SPACE_KEY}
      - MAX_SLACK_MSG_LENGTH=${MAX_SLACK_MSG_LENGTH}
      # Make sure to include these environment variables if they are used by your bot
      - RUNWAY_API_KEY=${RUNWAY_API_KEY}
      - RUNWAY_BASE_URL=${RUNWAY_BASE_URL:-https://api.runway.team/v1}
      - RUNWAY_ORG_ID=${RUNWAY_ORG_ID}
      - RUNWAY_APP_ID=${RUNWAY_APP_ID}
      - GITHUB_TOKEN=${GITHUB_TOKEN}               
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME} 
    command: uvicorn bot.main:app --host 0.0.0.0 --port 8004
    networks:
      - gidchatbot_default

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: "http bot:8004" # CHANGED FROM "http bot.main:8004"
    ports:
      - "4040:4040"
    networks:
      - gidchatbot_default

networks:
  gidchatbot_default: